// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gttvhadmroffvyscotjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0dHZoYWRtcm9mZnZ5c2NvdGpyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3OTIyNTAsImV4cCI6MjA2NjM2ODI1MH0.InaM3k96KFBjsChkwAK5FZcByDMipBpbcF-GKd_T4ZU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});